task/PP-8995: Centi & Heidipay for Shopware 5
payrexx/shopware-payrexx-gateway pull request #7
Opened 2023-04-26 12:24 UTC by vinothss4u

2023-04-26 13:05 UTC, vekkon requested changes
When the plugin is updated, all payment methods are deactivated. Please improve the update process

2023-05-01 06:48 UTC, michaelraess approved these changes

2023-05-01 06:48 UTC, michaelraess approved these changes

2023-05-01 06:49 UTC, michaelraess approved these changes

2023-05-08 08:32 UTC, jdluca22 commented on PayrexxPaymentGateway/PayrexxPaymentGateway.php
> +            'heidipay' => 'Heidipay',
Change default name to 'Ratenzahlung mit Heidipay'

2023-05-08 11:51 UTC, markusliechti approved these changes

2023-05-08 13:17 UTC, merged